version: '3.7'
services:
  flask_app:
    image: sourishx/flaskapp:01
    build: flask_app

  nginx:
    image: sourishx/nginx:01
    container_name: nginx
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app